chunk = integer(default=1024)
rate = integer(default=16000)
buffer = integer(default=5)
port = integer(default=8800)
bind = string(default='0.0.0.0')
sleep_interval = float(default=0.1)
activity_timeout = float(default=1.0)
